name: Check typing

on:
  push:

jobs:
  check_typing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
      fail-fast: false

  steps:
  - uses: actions/checkout@v3
  - run: pipx install poetry
  - uses: actions/setup-python@v4
    with:
      cache: 'poetry'
  - run: poetry install
  - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
  - uses: jakebailey/pyright-action@v2
    with:
      pylance-version: latest-release
